# Generated by Django 3.2.6 on 2021-08-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliefAPI', '0002_alter_videolink_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolink',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
