# Generated by Django 3.2.6 on 2021-08-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reliefAPI', '0003_alter_videolink_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolink',
            name='date',
        ),
    ]
