# Generated by Django 3.2.6 on 2021-08-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reliefAPI', '0005_auto_20210812_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolink',
            name='name',
        ),
    ]
